translations = {
    'Австралия': 'Australia',
    'Австрия': 'Austria',
    'Алжир': 'Algeria',
    'Аргентина': 'Argentina',
    'Беларусь': 'Belarus',
    'Бельгия': 'Belgium',
    'Болгария': 'Bulgaria',
    'Бразилия': 'Brazil',
    'Великобритания': 'United Kingdom',
    'Венгрия': 'Hungary',
    'Германия': 'Germany',
    'Гонконг': 'Hong Kong',
    'Дания': 'Denmark',
    'Израиль': 'Israel',
    'Индия': 'India',
    'Индонезия': 'Indonesia',
    'Иран': 'Iran',
    'Ирландия': 'Ireland',
    'Исландия': 'Iceland',
    'Испания': 'Spain',
    'Италия': 'Italy',
    'Казахстан': 'Kazakhstan',
    'Канада': 'Canada',
    'Кения': 'Kenya',
    'Кипр': 'Cyprus',
    'Китай': 'China',
    'Колумбия': 'Colombia',
    'Коста-Рика': 'Costa Rica',
    'Куба': 'Cuba',
    'Латвия': 'Latvia',
    'Маврикий': 'Mauritius',
    'Мексика': 'Mexico',
    'Молдова': 'Moldova',
    'Нидерланды': 'Netherlands',
    'Новая Зеландия': 'New Zealand',
    'Норвегия': 'Norway',
    'Польша': 'Poland',
    'Португалия': 'Portugal',
    'Пуэрто-Рико': 'Puerto Rico',
    'Республика Корея': 'South Korea',
    'Россия': 'Russia',
    'СССР': 'Soviet Union',
    'США': 'United States of America',
    'Сербия': 'Serbia',
    'Таиланд': 'Thailand',
    'Тайвань': 'Taiwan',
    'Турция': 'Turkey',
    'Узбекистан': 'Uzbekistan',
    'Украина': 'Ukraine',
    'Финляндия': 'Finland',
    'Франция': 'France',
    'Хорватия': 'Croatia',
    'Чехия': 'Czechia',
    'Швейцария': 'Switzerland',
    'Швеция': 'Sweden',
    'Эстония': 'Estonia',
    'ЮАР': 'South Africa',
    'Япония': 'Japan'
}

